# -*- coding: utf-8 -*-
"""som_case_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLaFFB7i9ERXeV5LDtt813WqZmVPFl-h

# Part 1 - SOM
"""
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

dataset = pd.read_csv('Credit_Card_Applications.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Feature Scaling

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
X = sc.fit_transform(X)

# Training the SOM
from minisom import MiniSom
# sigma: radius of different neighbors from the grid
# learning_rate: hyperparameter with which weights are updated each iteration
# x, y dimension of som. Not too small (miss outliners) and not too large(needs huge data to get accurate outliners).
som = MiniSom(x = 10, y = 10, input_len=15, sigma=1.0, learning_rate=0.5)
som.random_weights_init(X)
som.train_random(data=X, num_iteration=100)

"""# Visualizing the results"""

from pylab import bone, pcolor, colorbar, plot, show
bone()
pcolor(som.distance_map().T)
colorbar()
markers = ['o', 's']
colors = ['r', 'g']
for i, x in enumerate(X):
    w = som.winner(x)
    plot(w[0] + 0.5,
         w[1] + 0.5,
         markers[y[i]],
         markeredgecolor = colors[y[i]],
         markerfacecolor = 'None',
         markersize = 10,
         markeredgewidth = 2)
show()

"""# Finding the frauds"""

mappings = som.win_map(X)

frauds = []

for node in [(2,7), (1,6), (2,6)]:
    if node in mappings:
        frauds.extend(mappings[node])

frauds = np.array(frauds)
frauds = sc.inverse_transform(frauds)
print(frauds)

# Printing the Fradulent clients

print('Fraud Customer IDs')
for i in frauds[:, 0]:
  print(int(i))

"""# Going from Unsupervised to Supervised Deep Learning"""

# Creating the Matrix of Features
customers = dataset.iloc[:,1:].values

# Creating the dependent variable
is_fraud = np.zeros(len(dataset))
for i in range(len(dataset)):
  if dataset.iloc[i,0] in frauds:
    is_fraud[i] = 1

# ANN
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
customers = sc.fit_transform(customers)

# Builind ANN

import tensorflow as tf
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=2, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training ANN
ann.fit(customers, is_fraud, batch_size = 1, epochs = 15)

"""# Predicting the test set results"""

y_pred = ann.predict(customers)
y_pred = np.concatenate((dataset.iloc[:, 0:1].values, y_pred), axis = 1)
y_pred = y_pred[y_pred[:, 1].argsort()]

